sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1

matrix:
    allow_failures:
      - php: 7.1

env:
  - CFG_DB_HOST=127.0.0.1 CFG_DB_PORT=3306 CFG_DB_USER=travis CFG_DB_PASS= CFG_DB=dbal_test

before_script:
  - mysql -e "create database IF NOT EXISTS dbal_test;" -uroot

install:
  - composer self-update && composer install

